dist: precise

language: php

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - REDIS_HOST=localhost REDIS_PASSWORD= ./vendor/bin/phpunit